spring:
  application:
    name: user-ui

  main:
    banner-mode: "off"

  output:
    ansi:
      enabled: "ALWAYS"

  config:
    import: optional:configserver:http://localhost:8084/

management:
  endpoints:
    web:
      exposure:
        include: "*"
